<?php
/**
 * File containing the eZ\Publish\API\Repository\URLAliasService class.
 *
 * @copyright Copyright (C) 1999-2012 eZ Systems AS. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 * @version //autogentag//
 * @package eZ\Publish\API\Repository
 */

namespace eZ\Publish\API\Repository;

use eZ\Publish\API\Repository\Values\Content\Location;

/**
 * URLAlias service
 *
 * @example Examples/urlalias.php
 *
 * @package eZ\Publish\API\Repository
 */
interface URLAliasService
{
     /**
     * Create a user chosen $alias pointing to $location in $languageCode.
     * 
     * This method runs URL filters and transformers before storing them.
     * Hence the path returned in the URLAlias Value may differ from the given.
     * $alwaysAvailable makes the alias available in all languages.
     *
     * @param \eZ\Publish\API\Repository\Values\Content\Location $location
     * @param string $path
     * @param boolean $forward if true a redirect is performed
     * @param string $languageCode the languageCode for which this alias is valid
     * @param boolean $alwaysAvailable 
     * 
     * @throws \eZ\Publish\API\Repository\Exceptions\ForbiddenException if the path already exists for the given language
     * 
     * @return \eZ\Publish\API\Repository\Values\Content\URLAlias
     */
    public function createUrlAlias(Location $location, $path,  $languageCode, $forward = false, $alwaysAvailable = false );
    
     /**
     * Create a user chosen $alias pointing to a resource in $languageName.
     * 
     * This method does not handle location resources - if a user enters a location target
     * the createCustomUrlAlias method has to be used.
     * This method runs URL filters and and transformers before storing them.
     * Hence the path returned in the URLAlias Value may differ from the given.
     * 
     * $alwaysAvailable makes the alias available in all languages.
     *
     * @param string $resource
     * @param string $path
     * @param boolean $forwarding
     * @param string $languageName
     * @param boolean $alwaysAvailable
     * 
     * @throws \eZ\Publish\API\Repository\Exceptions\ForbiddenException if the path already exists for the given language
     * 
     * @return \eZ\Publish\API\Repository\Values\Content\URLAlias
     */
    public function createGlobalUrlAlias(  $resource, $path, $languageCode, $forward = false, $alwaysAvailable = false );
    
     /**
     * List of url aliases pointing to $location.
     * 
     * @todo may be there is a need for a function which returns one URL Alias based on a prioritized language
     * 
     * @param \eZ\Publish\API\Repository\Values\Content\Location $location
     * @param $custom if true the user generated aliases are listed otherwise the autogenerated
     * @param string $languageCode filters those which are valid for the given language
     * 
     * @return \eZ\Publish\API\Repository\Values\Content\URLAlias[]
     */
    public function listLocationAliases( Location $location, $custom = true, $languageCode = null );

    /**
     * List global aliases
     * 
     * @param string $languageCode filters those which are valid for the given language
     * @param int $offset
     * @param int limit
     * 
     * @return \eZ\Publish\API\Repository\Values\Content\URLAlias[]
     */
    public function listGlobalAliases($languageCode = null, $offset = 0, $limit = -1);
    
    
    /**
     * Removes urls aliases.
     * 
     * This method does not remove autogenerated aliases for locations.
     *
     * @param \eZ\Publish\API\Repository\Values\Content\URLAlias[] $aliasList
     * @return boolean
     */
    public function removeAliases( array $aliasList );
    
    /**
     * looks up the URLAlias for the given url 
     * 
     * @param string $url
     * @param string $languageCode
     * 
     * @throws \eZ\Publish\API\Repository\Exceptions\NotFoundException if the path does not exist or is not valid for the given language
     * 
     * @return \eZ\Publish\API\Repository\Values\Content\URLAlias 
     */
    public function lookUp($url, $languageCode = null);
    
    
    
}
