parameters:
    ezpublish.solr.engine_factory.class: eZ\Bundle\EzPublishSolrSearchEngineBundle\ApiLoader\SolrEngineFactory
    ez_search_engine_solr.default_connection: ~

services:
    ezpublish.solr.engine_factory:
        class: %ezpublish.solr.engine_factory.class%
        arguments:
            - @ezpublish.api.repository_configuration_provider
            - %ez_search_engine_solr.default_connection%
            - %ezpublish.spi.search.solr.class%
        calls:
            - [setContainer, [@service_container]]
