<?php

return array(
    'ezcontentclass' => array(
        array(
            'id' => 1,
            'always_available' => 1,
            'contentobject_name' => '<short_name|name>',
            'created' => 1024392098,
            'creator_id' => 14,
            'identifier' => 'folder',
            'initial_language_id' => 2,
            'is_container' => 1,
            'language_mask' => 3,
            'modified' => 1082454875,
            'modifier_id' => 14,
            'remote_id' => 'a3d405b81be900468eb153d774f4f0d2',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:6:"Folder";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => '',
            'version' => 1
        ),
        array(
            'id' => 2,
            'always_available' => 1,
            'contentobject_name' => '<short_name|name>',
            'created' => 1024392098,
            'creator_id' => 14,
            'identifier' => 'folder_3',
            'initial_language_id' => 2,
            'is_container' => 1,
            'language_mask' => 3,
            'modified' => 1082454875,
            'modifier_id' => 14,
            'remote_id' => 'a3d405b81be900468eb153d774f4f0d2',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:6:"Folder";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => '',
            'version' => 0
        ),
    ),
    'ezcontentclass_attribute' => array(
        array(
            'id' => 4,
            'contentclass_id' => 1,
            'can_translate' => 1,
            'category' => '',
            'data_float1' => 0,
            'data_float2' => 0,
            'data_float3' => 0,
            'data_float4' => 0,
            'data_int1' => 255,
            'data_int2' => 0,
            'data_int3' => 0,
            'data_int4' => 0,
            'data_text1' => 'Folder',
            'data_text2' => '',
            'data_text3' => '',
            'data_text4' => '',
            'data_text5' => '',
            'data_type_string' => 'ezstring',
            'identifier' => 'name',
            'is_information_collector' => 0,
            'is_required' => 1,
            'is_searchable' => 1,
            'placement' => 1,
            'serialized_data_text' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:4:"Name";}',
            'version' => 1
        ),
        array(
            'id' => 119,
            'contentclass_id' => 1,
            'can_translate' => 1,
            'category' => '',
            'data_float1' => 0,
            'data_float2' => 0,
            'data_float3' => 0,
            'data_float4' => 0,
            'data_int1' => 5,
            'data_int2' => 0,
            'data_int3' => 0,
            'data_int4' => 0,
            'data_text1' => '',
            'data_text2' => '',
            'data_text3' => '',
            'data_text4' => '',
            'data_text5' => '',
            'data_type_string' => 'ezxmltext',
            'identifier' => 'short_description',
            'is_information_collector' => 0,
            'is_required' => 0,
            'is_searchable' => 1,
            'placement' => 3,
            'serialized_data_text' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:17:"Short description";}',
            'version' => 1
        ),
        array(
            'id' => 155,
            'contentclass_id' => 1,
            'can_translate' => 1,
            'category' => '',
            'data_float1' => 0,
            'data_float2' => 0,
            'data_float3' => 0,
            'data_float4' => 0,
            'data_int1' => 100,
            'data_int2' => 0,
            'data_int3' => 0,
            'data_int4' => 0,
            'data_text1' => '',
            'data_text2' => '',
            'data_text3' => '',
            'data_text4' => '',
            'data_text5' => '',
            'data_type_string' => 'ezstring',
            'identifier' => 'short_name',
            'is_information_collector' => 0,
            'is_required' => 0,
            'is_searchable' => 1,
            'placement' => 2,
            'serialized_data_text' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:10:"Short name";}',
            'version' => 1
        ),
        array(
            'id' => 156,
            'contentclass_id' => 1,
            'can_translate' => 1,
            'category' => '',
            'data_float1' => 0,
            'data_float2' => 0,
            'data_float3' => 0,
            'data_float4' => 0,
            'data_int1' => 20,
            'data_int2' => 0,
            'data_int3' => 0,
            'data_int4' => 0,
            'data_text1' => '',
            'data_text2' => '',
            'data_text3' => '',
            'data_text4' => '',
            'data_text5' => '',
            'data_type_string' => 'ezxmltext',
            'identifier' => 'description',
            'is_information_collector' => 0,
            'is_required' => 0,
            'is_searchable' => 1,
            'placement' => 4,
            'serialized_data_text' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:11:"Description";}',
            'version' => 1
        ),
        array(
            'id' => 158,
            'contentclass_id' => 1,
            'can_translate' => 0,
            'category' => '',
            'data_float1' => 0,
            'data_float2' => 0,
            'data_float3' => 0,
            'data_float4' => 0,
            'data_int1' => 0,
            'data_int2' => 0,
            'data_int3' => 1,
            'data_int4' => 0,
            'data_text1' => '',
            'data_text2' => '',
            'data_text3' => '',
            'data_text4' => '',
            'data_text5' => '',
            'data_type_string' => 'ezboolean',
            'identifier' => 'show_children',
            'is_information_collector' => 0,
            'is_required' => 0,
            'is_searchable' => 0,
            'placement' => 5,
            'serialized_data_text' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:13:"Show children";}',
            'version' => 1
        ),
        array(
            'id' => 160,
            'contentclass_id' => 2,
            'can_translate' => 0,
            'category' => '',
            'data_float1' => 0,
            'data_float2' => 0,
            'data_float3' => 0,
            'data_float4' => 0,
            'data_int1' => 0,
            'data_int2' => 0,
            'data_int3' => 1,
            'data_int4' => 0,
            'data_text1' => '',
            'data_text2' => '',
            'data_text3' => '',
            'data_text4' => '',
            'data_text5' => '',
            'data_type_string' => 'ezboolean',
            'identifier' => 'show_children',
            'is_information_collector' => 0,
            'is_required' => 0,
            'is_searchable' => 0,
            'placement' => 5,
            'serialized_data_text' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_description_list' => 'a:2:{i:0;s:0:"";s:16:"always-available";b:0;}',
            'serialized_name_list' => 'a:2:{s:16:"always-available";s:6:"eng-US";s:6:"eng-US";s:13:"Show children";}',
            'version' => 0
        ),
    ),
    'ezcontentclass_name' => array(
         array(
            'contentclass_id' => 1,
            'contentclass_version' => 1,
            'language_id' => 3,
            'language_locale' => 'eng-US',
            'name' => 'Folder'
        )
    ),
    'ezcontentclass_classgroup' => array(
        array(
            'contentclass_id' => 1,
            'contentclass_version' => 1,
            'group_id' => 1,
            'group_name' => 'Content'
        ),
        array(
            'contentclass_id' => 1,
            'contentclass_version' => 1,
            'group_id' => 4,
            'group_name' => 'Setup'
        )
    )
);
