<?php

return [
    'ezcontentobject_tree' => [
        0 => [
            'contentobject_id' => '0',
            'contentobject_is_published' => '1',
            'contentobject_version' => '1',
            'depth' => '0',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '1',
            'modified_subnode' => '1376485938',
            'node_id' => '1',
            'parent_node_id' => '1',
            'path_identification_string' => '',
            'path_string' => '/1/',
            'priority' => '0',
            'remote_id' => '629709ba256fe317c3ddcee35453a96a',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
        1 => [
            'contentobject_id' => '57',
            'contentobject_is_published' => '1',
            'contentobject_version' => '1',
            'depth' => '1',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '2',
            'modified_subnode' => '1376485938',
            'node_id' => '2',
            'parent_node_id' => '1',
            'path_identification_string' => '',
            'path_string' => '/1/2/',
            'priority' => '0',
            'remote_id' => 'f3e90596361e31d496d4026eb624c983',
            'sort_field' => '8',
            'sort_order' => '1',
        ],
        2 => [
            'contentobject_id' => '4',
            'contentobject_is_published' => '1',
            'contentobject_version' => '1',
            'depth' => '1',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '5',
            'modified_subnode' => '1376485938',
            'node_id' => '5',
            'parent_node_id' => '1',
            'path_identification_string' => 'users',
            'path_string' => '/1/5/',
            'priority' => '0',
            'remote_id' => '3f6d92f8044aed134f32153517850f5a',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
        3 => [
            'contentobject_id' => '11',
            'contentobject_is_published' => '1',
            'contentobject_version' => '2',
            'depth' => '2',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '12',
            'modified_subnode' => '1376485938',
            'node_id' => '12',
            'parent_node_id' => '5',
            'path_identification_string' => 'users/members',
            'path_string' => '/1/5/12/',
            'priority' => '0',
            'remote_id' => '602dcf84765e56b7f999eaafd3821dd3',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
        4 => [
            'contentobject_id' => '12',
            'contentobject_is_published' => '1',
            'contentobject_version' => '1',
            'depth' => '2',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '13',
            'modified_subnode' => '1376485937',
            'node_id' => '13',
            'parent_node_id' => '5',
            'path_identification_string' => 'users/administrator_users',
            'path_string' => '/1/5/13/',
            'priority' => '0',
            'remote_id' => '769380b7aa94541679167eab817ca893',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
        5 => [
            'contentobject_id' => '13',
            'contentobject_is_published' => '1',
            'contentobject_version' => '1',
            'depth' => '2',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '14',
            'modified_subnode' => '1081860719',
            'node_id' => '14',
            'parent_node_id' => '5',
            'path_identification_string' => 'users/editors',
            'path_string' => '/1/5/14/',
            'priority' => '0',
            'remote_id' => 'f7dda2854fc68f7c8455d9cb14bd04a9',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
        6 => [
            'contentobject_id' => '14',
            'contentobject_is_published' => '1',
            'contentobject_version' => '4',
            'depth' => '3',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '15',
            'modified_subnode' => '1376485937',
            'node_id' => '15',
            'parent_node_id' => '13',
            'path_identification_string' => 'users/administrator_users/administrator_user',
            'path_string' => '/1/5/13/15/',
            'priority' => '0',
            'remote_id' => 'e5161a99f733200b9ed4e80f9c16187b',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
        14 => [
            'contentobject_id' => '52',
            'contentobject_is_published' => '1',
            'contentobject_version' => '1',
            'depth' => '2',
            'is_hidden' => '0',
            'is_invisible' => '0',
            'main_node_id' => '54',
            'modified_subnode' => '1184592117',
            'node_id' => '54',
            'parent_node_id' => '48',
            'path_identification_string' => 'setup2/common_ini_settings',
            'path_string' => '/1/48/54/',
            'priority' => '0',
            'remote_id' => 'fa9f3cff9cf90ecfae335718dcbddfe2',
            'sort_field' => '1',
            'sort_order' => '1',
        ],
    ],
    'ezuser' => [
        0 => [
            'contentobject_id' => '14',
            'email' => 'foo@example.com',
            'login' => 'admin',
            'password_hash' => 'publish',
            'password_hash_type' => '5',
        ],
    ],
    'ezcontentbrowsebookmark' => [
        0 => [
            'id' => '1',
            'name' => 'Lorem ipsum dolor',
            'node_id' => '5',
            'user_id' => '14',
        ],
        1 => [
            'id' => '3',
            'name' => '',
            'node_id' => '12',
            'user_id' => '14',
        ],
        2 => [
            'id' => '4',
            'name' => '',
            'node_id' => '13',
            'user_id' => '14',
        ],
        3 => [
            'id' => '5',
            'name' => '',
            'node_id' => '15',
            'user_id' => '14',
        ],
        4 => [
            'id' => '6',
            'name' => '',
            'node_id' => '14',
            'user_id' => '14',
        ],
    ],
];
