services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eZ\Publish\Core\Repository\EventSubscriber\:
        resource: '../../../eZ/Publish/Core/Repository/EventSubscriber/*'
