parameters:
    # Rich Text Custom Tags global configuration
    ezplatform.ezrichtext.custom_tags: {}
    # Rich Text Custom Tags default scope (for SiteAccess) configuration
    ezsettings.default.fieldtypes.ezrichtext.custom_tags: []

    # Rich Text Custom Styles global configuration
    ezplatform.ezrichtext.custom_styles: {}
    # Rich Text Custom Styles default scope (for SiteAccess) configuration
    ezsettings.default.fieldtypes.ezrichtext.custom_styles: []

    # Default XSL stylesheets for RichText rendering to HTML5.
    # Built-in stylesheets are treated as custom for the sake of extensibility.
    ezsettings.default.fieldtypes.ezrichtext.output_custom_xsl:
        -
            path: '%kernel.root_dir%/../vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl'
            priority: 0

    ezsettings.default.fieldtypes.ezrichtext.edit_custom_xsl:
        -
            path: '%kernel.root_dir%/../vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl'
            priority: 0

    ezsettings.default.fieldtypes.ezrichtext.input_custom_xsl: []

    # RichText field type template tag settings
    # 'default' and 'default_inline' tag identifiers are reserved for fallback
    ezsettings.default.fieldtypes.ezrichtext.tags.default:
        template: EzPublishCoreBundle:FieldType/RichText/tag:default.html.twig
    ezsettings.default.fieldtypes.ezrichtext.tags.default_inline:
        template: EzPublishCoreBundle:FieldType/RichText/tag:default_inline.html.twig

    # RichText field type template style settings
    # 'default' and 'default_inline' tag identifiers are reserved for fallback
    ezsettings.default.fieldtypes.ezrichtext.styles.default:
        template: EzPublishCoreBundle:FieldType/RichText/style:default.html.twig
    ezsettings.default.fieldtypes.ezrichtext.styles.default_inline:
        template: EzPublishCoreBundle:FieldType/RichText/style:default_inline.html.twig

    # RichText field type embed settings
    ezsettings.default.fieldtypes.ezrichtext.embed.content:
        template: EzPublishCoreBundle:FieldType/RichText/embed:content.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.content_denied:
        template: EzPublishCoreBundle:FieldType/RichText/embed:content_denied.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.content_inline:
        template: EzPublishCoreBundle:FieldType/RichText/embed:content_inline.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.content_inline_denied:
        template: EzPublishCoreBundle:FieldType/RichText/embed:content_inline_denied.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.location:
        template: EzPublishCoreBundle:FieldType/RichText/embed:location.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.location_denied:
        template: EzPublishCoreBundle:FieldType/RichText/embed:location_denied.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.location_inline:
        template: EzPublishCoreBundle:FieldType/RichText/embed:location_inline.html.twig
    ezsettings.default.fieldtypes.ezrichtext.embed.location_inline_denied:
        template: EzPublishCoreBundle:FieldType/RichText/embed:location_inline_denied.html.twig
