<?php

return array(
    'ezurlalias_ml' => array(
        0 => array(
            'action' => 'eznode:2',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '1',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '3',
            'link' => '1',
            'parent' => '0',
            'text' => '',
            'text_md5' => 'd41d8cd98f00b204e9800998ecf8427e',
        ),
        1 => array(
            'action' => 'eznode:314',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '2',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '2',
            'parent' => '0',
            'text' => 'jedan',
            'text_md5' => '6896260129051a949051c3847c34466f',
        ),
        2 => array(
            'action' => 'eznode:315',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '3',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '3',
            'parent' => '0',
            'text' => 'dva',
            'text_md5' => 'c67ed9a09ab136fae610b6a087d82e21',
        ),
        3 => array(
            'action' => 'eznode:316',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '8',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '2',
            'link' => '4',
            'parent' => '2',
            'text' => 'swap-that',
            'text_md5' => 'b8d555a5436774b6d3a035a4437ea37c',
        ),
        4 => array(
            'action' => 'eznode:317',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '9',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '2',
            'link' => '5',
            'parent' => '3',
            'text' => 'swap-this',
            'text_md5' => '21940df6bebbfc9501b3b512640dffe5',
        ),
        5 => array(
            'action' => 'eznode:318',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '6',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '6',
            'parent' => '2',
            'text' => 'swap-this',
            'text_md5' => '21940df6bebbfc9501b3b512640dffe5',
        ),
        6 => array(
            'action' => 'eznode:319',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '7',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '7',
            'parent' => '3',
            'text' => 'swap-that',
            'text_md5' => 'b8d555a5436774b6d3a035a4437ea37c',
        ),
        7 => array(
            'action' => 'eznode:316',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '4',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '2',
            'link' => '4',
            'parent' => '2',
            'text' => 'swap-not-that',
            'text_md5' => 'd28a35f7595771f6a0be76f0b890715a',
        ),
        8 => array(
            'action' => 'eznode:317',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '5',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '2',
            'link' => '5',
            'parent' => '3',
            'text' => 'swap-not-this',
            'text_md5' => '2b78a26576e43f93e266cb502ff1dece',
        ),
    ),
    'ezcontent_language' => array(
        0 => array(
            'disabled' => 0,
            'id' => 2,
            'locale' => 'cro-HR',
            'name' => 'Croatian (Hrvatski)'
        ),
    ),
    'ezurlalias_ml_incr' => array(
        0 => array(
            'id' => '1',
        ),
        1 => array(
            'id' => '2',
        ),
        2 => array(
            'id' => '3',
        ),
        3 => array(
            'id' => '4',
        ),
        4 => array(
            'id' => '5',
        ),
        5 => array(
            'id' => '6',
        ),
        6 => array(
            'id' => '7',
        ),
        7 => array(
            'id' => '8',
        ),
        8 => array(
            'id' => '9',
        ),
    ),
);
