<?php

return array(
    'ezurlalias_ml' => array(
        0 => array(
            'action' => 'eznode:2',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '1',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '3',
            'link' => '1',
            'parent' => '0',
            'text' => '',
            'text_md5' => 'd41d8cd98f00b204e9800998ecf8427e',
        ),
        1 => array(
            'action' => 'eznode:3',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '2',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '2',
            'parent' => '0',
            'text' => 'moved-parent',
            'text_md5' => 'b3c65c78b56bcec4b9884dd694088379',
        ),
        2 => array(
            'action' => 'eznode:4',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '3',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '3',
            'parent' => '2',
            'text' => 'moved',
            'text_md5' => '11dfd868d93bc2b0e4ce0bee5756f8b1',
        ),
        4 => array(
            'action' => 'eznode:5',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '4',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '4',
            'parent' => '0',
            'text' => 'moved-original-parent',
            'text_md5' => '6b01ae8cd40d07ea8be54bbddc9a42f8',
        ),
        5 => array(
            'action' => 'eznode:4',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '5',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '4',
            'link' => '3',
            'parent' => '4',
            'text' => 'moved-history',
            'text_md5' => '7e6a74afb9efb5db7d18fdbd2edecaec',
        ),
        6 => array(
            'action' => 'eznode:6',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '6',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '6',
            'parent' => '3',
            'text' => 'sub',
            'text_md5' => '8a68dc3e925eacf92633be230722a140',
        ),
        7 => array(
            'action' => 'eznode:7',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '7',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '4',
            'link' => '6',
            'parent' => '3',
            'text' => 'sub-history',
            'text_md5' => 'e9f37abc40f517ebd795873f2683e690',
        ),
        8 => array(
            'action' => 'eznode:4',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '8',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '4',
            'link' => '3',
            'parent' => '0',
            'text' => 'moved-previous-history',
            'text_md5' => '520472b9a76d8980eefc68bf519aa446',
        ),
        9 => array(
            'action' => 'eznode:8',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '9',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '9',
            'parent' => '4',
            'text' => 'sub2',
            'text_md5' => '5fbef65269a99bddc2106251dd89b1dc',
        ),
        10 => array(
            'action' => 'nop:',
            'action_type' => 'nop',
            'alias_redirects' => '1',
            'id' => '10',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '1',
            'link' => '10',
            'parent' => '0',
            'text' => 'custom-below',
            'text_md5' => '4fedee449bc4573f786d5839bf39ef31',
        ),
        11 => array(
            'action' => 'eznode:5',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '11',
            'is_alias' => '1',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '11',
            'parent' => '10',
            'text' => 'moved-original-parent-custom',
            'text_md5' => '1098a946541fe683a50fb569b13a2fd9',
        ),
        12 => array(
            'action' => 'eznode:5',
            'action_type' => 'eznode',
            'alias_redirects' => '0',
            'id' => '12',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '4',
            'link' => '4',
            'parent' => '0',
            'text' => 'moved-original-parent-history',
            'text_md5' => '1098a946541fe683a50fb569b13a2fd9',
        ),
    ),
    'ezurlalias_ml_incr' => array(
        0 => array(
            'id' => '1',
        ),
        1 => array(
            'id' => '2',
        ),
        2 => array(
            'id' => '3',
        ),
        3 => array(
            'id' => '4',
        ),
        4 => array(
            'id' => '5',
        ),
        5 => array(
            'id' => '6',
        ),
        6 => array(
            'id' => '7',
        ),
        7 => array(
            'id' => '8',
        ),
        8 => array(
            'id' => '9',
        ),
        9 => array(
            'id' => '10',
        ),
        10 => array(
            'id' => '11',
        ),
        11 => array(
            'id' => '12',
        ),
    ),
    'ezcontent_language' => array(
        0 => array(
            'disabled' => 0,
            'id' => 2,
            'locale' => 'cro-HR',
            'name' => 'Croatian (Hrvatski)'
        ),
        1 => array(
            'disabled' => 0,
            'id' => 4,
            'locale' => 'eng-GB',
            'name' => 'English (United Kingdom)'
        ),
    ),
);
