<?php

return array(
    'ezurlalias_ml' => array(
        0 => array(
            'action' => 'eznode:2',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '1',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '3',
            'link' => '1',
            'parent' => '0',
            'text' => '',
            'text_md5' => 'd41d8cd98f00b204e9800998ecf8427e',
        ),
        1 => array(
            'action' => 'eznode:314',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '2',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '2',
            'parent' => '0',
            'text' => 'jedan',
            'text_md5' => '6896260129051a949051c3847c34466f',
        ),
        2 => array(
            'action' => 'eznode:314',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '2',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '4',
            'link' => '2',
            'parent' => '0',
            'text' => 'one',
            'text_md5' => 'f97c5d29941bfb1b2fdab0874906ab82',
        ),
        3 => array(
            'action' => 'eznode:315',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '3',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '3',
            'parent' => '0',
            'text' => 'dva',
            'text_md5' => 'c67ed9a09ab136fae610b6a087d82e21',
        ),
        4 => array(
            'action' => 'eznode:315',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '3',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '8',
            'link' => '3',
            'parent' => '0',
            'text' => 'zwei',
            'text_md5' => '15d55d085e6eda9586293acad7c0a4f4',
        ),
    ),
    'ezcontent_language' => array(
        0 => array(
            'disabled' => 0,
            'id' => 2,
            'locale' => 'cro-HR',
            'name' => 'Croatian (Hrvatski)',
        ),
        1 => array(
            'disabled' => 0,
            'id' => 4,
            'locale' => 'eng-GB',
            'name' => 'English (United Kingdom)',
        ),
        2 => array(
            'disabled' => 0,
            'id' => 8,
            'locale' => 'ger-DE',
            'name' => 'German',
        ),
    ),
    'ezurlalias_ml_incr' => array(
        0 => array(
            'id' => '1',
        ),
        1 => array(
            'id' => '2',
        ),
        2 => array(
            'id' => '3',
        ),
    ),
    'ezcontentobject_tree' => array(
        0 => array(
            'node_id' => 2,
            'main_node_id' => 2,
            'parent_node_id' => 1,
            'path_string' => '',
            'path_identification_string' => '',
            'remote_id' => '',
            'contentobject_id' => 1,
        ),
        1 => array(
            'node_id' => 314,
            'main_node_id' => 314,
            'parent_node_id' => 2,
            'path_string' => '',
            'path_identification_string' => 'jedan',
            'remote_id' => '',
            'contentobject_id' => 2,
        ),
        2 => array(
            'node_id' => 315,
            'main_node_id' => 315,
            'parent_node_id' => 2,
            'path_string' => '',
            'path_identification_string' => 'zwei',
            'remote_id' => '',
            'contentobject_id' => 3,
        ),
    ),
    'ezcontentobject' => array(
        0 => array(
            'id' => 2,
            'initial_language_id' => 2,
            'current_version' => 1,
        ),
        1 => array(
            'id' => 3,
            'initial_language_id' => 8,
            'current_version' => 1,
        ),
    ),
    'ezcontentobject_name' => [
        0 => [
            'contentobject_id' => 2,
            'content_version' => 1,
            'name' => 'dva',
            'content_translation' => 'cro-HR',
        ],
        1 => [
            'contentobject_id' => 2,
            'content_version' => 1,
            'name' => 'zwei',
            'content_translation' => 'ger-DE',
        ],
        2 => [
            'contentobject_id' => 3,
            'content_version' => 1,
            'name' => 'jedan',
            'content_translation' => 'cro-HR',
        ],
        3 => [
            'contentobject_id' => 3,
            'content_version' => 1,
            'name' => 'one',
            'content_translation' => 'eng-GB',
        ],
    ],
);
