<?php

return array(
    'ezcontentobject_attribute' => array(
        0 => array(
            'attribute_original_id' => '0',
            'contentclassattribute_id' => '7',
            'contentobject_id' => '4',
            'data_float' => null,
            'data_int' => null,
            'data_text' => 'Main group',
            'data_type_string' => 'ezstring',
            'id' => '7',
            'language_code' => 'eng-US',
            'language_id' => '2',
            'sort_key_int' => '0',
            'sort_key_string' => 'main group',
            'version' => '1',
        ),
        1 => array(
            'attribute_original_id' => '0',
            'contentclassattribute_id' => '7',
            'contentobject_id' => '4',
            'data_float' => null,
            'data_int' => null,
            'data_text' => 'Glavna skupina',
            'data_type_string' => 'ezstring',
            'id' => '8',
            'language_code' => 'cro-HR',
            'language_id' => '5',
            'sort_key_int' => '0',
            'sort_key_string' => 'glavna skupina',
            'version' => '1',
        ),
        2 => array(
            'attribute_original_id' => '0',
            'contentclassattribute_id' => '7',
            'contentobject_id' => '4',
            'data_float' => null,
            'data_int' => null,
            'data_text' => 'Main group 2',
            'data_type_string' => 'ezstring',
            'id' => '7',
            'language_code' => 'eng-US',
            'language_id' => '3',
            'sort_key_int' => '0',
            'sort_key_string' => 'main group 2',
            'version' => '2',
        ),
        3 => array(
            'attribute_original_id' => '0',
            'contentclassattribute_id' => '7',
            'contentobject_id' => '4',
            'data_float' => null,
            'data_int' => null,
            'data_text' => 'Glavna skupina 2',
            'data_type_string' => 'ezstring',
            'id' => '8',
            'language_code' => 'cro-HR',
            'language_id' => '4',
            'sort_key_int' => '0',
            'sort_key_string' => 'glavna skupina 2',
            'version' => '2',
        ),
    ),
    'ezcontentobject_name' => array(),
    'ezcontentobject' => array(
        0 => array(
            'contentclass_id' => '3',
            'current_version' => '2',
            'id' => '4',
            'initial_language_id' => '2',
            'language_mask' => '7',
            'modified' => '1033917596',
            'name' => 'Users',
            'owner_id' => '14',
            'published' => '1033917596',
            'remote_id' => 'f5c88a2209584891056f987fd965b0ba',
            'section_id' => '2',
            'status' => '1',
        ),
    ),
);
