<?php

return array(
  0 =>
  array(
    'ezcontentobject_version_id' => '439',
    'ezcontentobject_version_version' => '1',
    'ezcontentobject_version_modified' => '1033920746',
    'ezcontentobject_version_creator_id' => '14',
    'ezcontentobject_version_created' => '1033920737',
    'ezcontentobject_version_status' => '3',
    'ezcontentobject_version_initial_language_id' => '2',
    'ezcontentobject_version_language_mask' => '3',
    'ezcontentobject_tree_main_node_id' => '12',
    'ezcontentobject_id' => '11',
    'ezcontentobject_contentclass_id' => '3',
    'ezcontentobject_section_id' => '2',
    'ezcontentobject_owner_id' => '14',
    'ezcontentobject_remote_id' => '5f7f0bdb3381d6a461d8c29ff53d908f',
    'ezcontentobject_current_version' => '2',
    'ezcontentobject_initial_language_id' => '2',
    'ezcontentobject_modified' => '1311154215',
    'ezcontentobject_published' => '1033920746',
    'ezcontentobject_status' => '1',
    'ezcontentobject_name' => 'Members',
    'ezcontentobject_language_mask' => '3',
    'ezcontentobject_is_hidden' => '0',
  ),
  1 =>
  array(
    'ezcontentobject_version_id' => '674',
    'ezcontentobject_version_version' => '2',
    'ezcontentobject_version_modified' => '1311154215',
    'ezcontentobject_version_creator_id' => '14',
    'ezcontentobject_version_created' => '1311154215',
    'ezcontentobject_version_status' => '1',
    'ezcontentobject_version_initial_language_id' => '2',
    'ezcontentobject_version_language_mask' => '3',
    'ezcontentobject_tree_main_node_id' => '12',
    'ezcontentobject_id' => '11',
    'ezcontentobject_contentclass_id' => '3',
    'ezcontentobject_section_id' => '2',
    'ezcontentobject_owner_id' => '14',
    'ezcontentobject_remote_id' => '5f7f0bdb3381d6a461d8c29ff53d908f',
    'ezcontentobject_current_version' => '2',
    'ezcontentobject_initial_language_id' => '2',
    'ezcontentobject_modified' => '1311154215',
    'ezcontentobject_published' => '1033920746',
    'ezcontentobject_status' => '1',
    'ezcontentobject_name' => 'Members',
    'ezcontentobject_language_mask' => '3',
    'ezcontentobject_is_hidden' => '0',
  ),
);
