<?php
/**
 * File containing the Storage interface
 *
 * @copyright Copyright (C) 1999-2011 eZ Systems AS. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 * @version //autogentag//
 *
 */

namespace ezp\Persistence\Fields;
use ezp\Persistence\Content\Field,
    ezp\Persistence\Content\FieldValue;

/**
 * Interface for setting field type data.
 *
 * Methods in this interface are called by storage engine.
 */
interface Storage
{
    /**
     * Stores $value for $fieldId in an external data source.
     *
     * Allows custom data types to store data in an external source.
     *
     * $fieldId = unique ID from the attribute tables (needs to be generated by
     * database back end on create, before the external data source may be
     * called from storing).
     *
     * @param int $fieldId
     * @param FieldValue $value
     * @return bool
     *
     */
    public function storeFieldData( $fieldId, FieldValue $value );

    /**
     * @param int $fieldId
     */
    public function getFieldData( $fieldId );

    /**
     * @param array $fieldId
     * @return bool
     */
    public function deleteFieldData( array $fieldId );

    /**
     * @return bool
     */
    public function hasFieldData();

    /**
     * @param int $fieldId
     */
    public function copyFieldData( $fieldId );

    /**
     * @param int $fieldId
     */
    public function getIndexData( $fieldId );
}
?>
