<?php
/**
 * File containing the Storage interface
 *
 * @copyright Copyright (C) 1999-2011 eZ Systems AS. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 * @version //autogentag//
 *
 */

namespace ezp\Persistence\Fields;
use ezp\Persistence\Content\Field,
    ezp\Persistence\Content\FieldValue;

/**
 * Interface for setting field type data.
 *
 * Methods in this interface are called by storage engine.
 */
interface Storage
{
    /**
     * Stores $value for $fieldId in an external data source.
     *
     * Allows custom data types to store data in an external source.
     *
     * $fieldId = unique ID from the attribute tables (needs to be generated by
     * database back end on create, before the external data source may be
     * called from storing).
     *
     * The context array provides some context for the field handler about the
     * currently used database engine. The array should at least define some
     * identifier and additionally pass some kind of connection handler.
     *
     * @param int $fieldId
     * @param FieldValue $value
     * @param array $context
     * @return bool
     *
     */
    public function storeFieldData( $fieldId, FieldValue $value, array $context );

    /**
     * Returns an updated field values based on the external data
     *
     * @param int $fieldId
     * @param FieldValue $value
     * @param array $context
     * @return FieldValue
     */
    public function getFieldData( $fieldId, FieldValue $value, array $context );

    /**
     * @param array $fieldId
     * @param array $context
     * @return bool
     */
    public function deleteFieldData( array $fieldId, array $context );

    /**
     * @return bool
     */
    public function hasFieldData();

    /**
     * @param int $fieldId
     * @param array $context
     */
    public function copyFieldData( $fieldId, array $context );

    /**
     * @param int $fieldId
     * @param array $context
     */
    public function getIndexData( $fieldId, array $context );
}
?>
