parameters:
#    ez_publish_io.example.class: eZ\Bundle\EzPublishIOBundle\Example

services:
#    ez_publish_io.example:
#        class: %ez_publish_io.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
