parameters:
    ezpublish.search.elasticsearch.content.gateway.client.http.stream.class: eZ\Publish\Core\Search\Elasticsearch\Content\Gateway\HttpClient\Stream
    ezpublish.search.elasticsearch.content.field_name_generator.class: eZ\Publish\Core\Search\Elasticsearch\Content\FieldNameGenerator

services:
    ezpublish.search.elasticsearch.content.gateway.client.http.stream:
        class: "%ezpublish.search.elasticsearch.content.gateway.client.http.stream.class%"
        arguments:
            - "%ezpublish.search.elasticsearch.connection.server%"

    ezpublish.search.elasticsearch.content.field_name_generator:
        class: "%ezpublish.search.elasticsearch.content.field_name_generator.class%"
