parameters:
    ezpublish.search.elasticsearch.content.gateway.client.http.stream.class: eZ\Publish\Core\Search\Elasticsearch\Content\Gateway\HttpClient\Stream
    ezpublish.search.elasticsearch.content.field_value_mapper.aggregate.class: eZ\Publish\Core\Search\Elasticsearch\Content\FieldValueMapper\Aggregate

services:
    ezpublish.search.elasticsearch.content.gateway.client.http.stream:
        class: %ezpublish.search.elasticsearch.content.gateway.client.http.stream.class%
        arguments:
            - %ezpublish.elasticsearch_server%

    # Note: services tagged with 'ezpublish.search.elasticsearch.content.field_value_mapper'
    # are registered to this one using compilation pass
    ezpublish.search.elasticsearch.content.field_value_mapper.aggregate:
        class: %ezpublish.search.elasticsearch.content.field_value_mapper.aggregate.class%

    # Mapping for our internal search field types
    ezpublish.search.elasticsearch.field_name_generator:
        class: %ezpublish.search.field_name_generator.class%
        arguments:
            -
                ez_integer: 'i'
                ez_id: 'id'
                ez_mid: 'mid'
                ez_string: 's'
                ez_mstring: 'ms'
                ez_long: 'l'
                ez_text: 't'
                ez_html: 'h'
                ez_boolean: 'b'
                ez_mboolean: 'mb'
                ez_float: 'f'
                ez_double: 'd'
                ez_date: 'dt'
                ez_point: 'p'
                ez_currency: 'c'
                ez_geolocation: 'gl'
                ez_document: 'doc'
