<?php
/**
 * File containing the XmlText\Value\OnlineEditor Value class
 *
 * @copyright Copyright (C) 1999-2011 eZ Systems AS. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 * @version //autogentag//
 */

namespace ezp\Content\FieldType\XmlText\Value;
use ezp\Content\FieldType\XmlText\Value;

/**
 * OnlineEditor value for TextLine field type.
 *
 * Takes as input the HTML generated by eZOE
 */
class OnlineEditor extends Value
{
}
