parameters:
    ezpublish.search.legacy.gateway.content.class: eZ\Publish\Core\Search\Legacy\Content\Gateway\DoctrineDatabase
    ezpublish.search.legacy.gateway.content.exception_conversion.class: eZ\Publish\Core\Search\Legacy\Content\Gateway\ExceptionConversion
    ezpublish.search.legacy.gateway.wordIndexer.class: eZ\Publish\Core\Search\Legacy\Content\WordIndexer\Gateway\DoctrineDatabase
    ezpublish.search.legacy.gateway.location.class: eZ\Publish\Core\Search\Legacy\Content\Location\Gateway\DoctrineDatabase
    ezpublish.search.legacy.gateway.location.exception_conversion.class: eZ\Publish\Core\Search\Legacy\Content\Location\Gateway\ExceptionConversion
    ezpublish.search.legacy.repository.searchIndex.class: eZ\Publish\Core\Search\Legacy\Content\WordIndexer\Repository\SearchIndex

services:
    ezpublish.search.legacy.gateway.content.inner:
        class: "%ezpublish.search.legacy.gateway.content.class%"
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
            - "@ezpublish.search.legacy.gateway.criteria_converter.content"
            - "@ezpublish.search.legacy.gateway.sort_clause_converter.content"
            - "@ezpublish.persistence.legacy.content_type.gateway"

    ezpublish.search.legacy.gateway.content.exception_conversion:
        class: "%ezpublish.search.legacy.gateway.content.exception_conversion.class%"
        arguments:
            - "@ezpublish.search.legacy.gateway.content.inner"

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.search.legacy.gateway.content:
        alias: ezpublish.search.legacy.gateway.content.exception_conversion


    ezpublish.search.legacy.gateway.wordIndexer:
        class: "%ezpublish.search.legacy.gateway.wordIndexer.class%"
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@ezpublish.api.storage_engine.transformation_processor"
            - "@ezpublish.search.legacy.repository.searchIndex"

    ezpublish.search.legacy.gateway.location.inner:
        class: "%ezpublish.search.legacy.gateway.location.class%"
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
            - "@ezpublish.search.legacy.gateway.criteria_converter.location"
            - "@ezpublish.search.legacy.gateway.sort_clause_converter.location"
            - "@ezpublish.persistence.legacy.content_type.gateway"

    ezpublish.search.legacy.gateway.location.exception_conversion:
        class: "%ezpublish.search.legacy.gateway.location.exception_conversion.class%"
        arguments:
            - "@ezpublish.search.legacy.gateway.location.inner"

    # To disable exception conversion layer override this alias so that it points to inner gateway
    ezpublish.search.legacy.gateway.location:
        alias: ezpublish.search.legacy.gateway.location.exception_conversion

    ezpublish.search.legacy.repository.searchIndex:
        class: "%ezpublish.search.legacy.repository.searchIndex.class%"
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
