<?php

/**
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
namespace eZ\Publish\Core\REST\Server\Values;

use eZ\Publish\Core\REST\Common\Value as RestValue;
use Symfony\Component\HttpFoundation\Response;

class DeletedUserSession extends RestValue
{
    /**
     * Response generated by RestAuthenticator.
     *
     * @see eZ\Publish\Core\MVC\Symfony\Security\Authentication\AuthenticatorInterface::logout()
     *
     * @var \Symfony\Component\HttpFoundation\Response
     */
    public $response;

    public function __construct(Response $response)
    {
        $this->response = $response;
    }
}
