services:
    ezplatform.installer.database.connection.factory:
        class: EzSystems\PlatformInstallerBundle\Database\ConnectionFactory
        arguments: ["@ezpublish.persistence.connection"]

    ezplatform.installer.database.connection:
        class: Doctrine\DBAL\Connection
        factory: ["@ezplatform.installer.database.connection.factory", createConnection]

    ezplatform.installer.database.dbms.mysql:
        class: EzSystems\PlatformInstallerBundle\Database\Platform\MySQLPlatform
        tags:
            - { name: ezplatform.installer.database, driver: pdo_mysql }
