<?php

/**
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace eZ\Bundle\EzPublishCoreBundle\Command;

use eZ\Publish\API\Repository\LocationService;
use eZ\Publish\API\Repository\PermissionResolver;
use eZ\Publish\API\Repository\SearchService;
use eZ\Publish\API\Repository\URLAliasService;
use eZ\Publish\API\Repository\UserService;
use eZ\Publish\API\Repository\Values\Content\LocationQuery;
use eZ\Publish\API\Repository\Values\Content\Query\Criterion\Subtree;
use eZ\Publish\Core\Pagination\Pagerfanta\LocationSearchAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * The ezplatform:urls:regenerate-aliases Symfony command implementation.
 * Recreates system URL aliases for all existing Locations and cleanups corrupted URL alias nodes.
 */
class RegenerateUrlAliasesCommand extends Command
{
    const DEFAULT_ITERATION_COUNT = 50;
    const DEFAULT_REPOSITORY_USER = 'admin';

    /**
     * @var \eZ\Publish\API\Repository\PermissionResolver
     */
    private $permissionResolver;

    /**
     * @var \eZ\Publish\API\Repository\UserService
     */
    private $userService;

    /**
     * @var \eZ\Publish\API\Repository\SearchService
     */
    private $searchService;

    /**
     * @var \eZ\Publish\API\Repository\LocationService
     */
    private $locationService;

    /**
     * @var \eZ\Publish\API\Repository\URLAliasService
     */
    private $urlAliasService;

    /**
     * @param \eZ\Publish\API\Repository\PermissionResolver $permissionResolver
     * @param \eZ\Publish\API\Repository\UserService $userService
     * @param \eZ\Publish\API\Repository\SearchService $searchService
     * @param \eZ\Publish\API\Repository\LocationService $locationService
     * @param \eZ\Publish\API\Repository\URLAliasService $urlAliasService
     */
    public function __construct(
        PermissionResolver $permissionResolver,
        UserService $userService,
        SearchService $searchService,
        LocationService $locationService,
        URLAliasService $urlAliasService
    ) {
        parent::__construct();

        $this->permissionResolver = $permissionResolver;
        $this->userService = $userService;
        $this->searchService = $searchService;
        $this->locationService = $locationService;
        $this->urlAliasService = $urlAliasService;
    }

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('ezplatform:urls:regenerate-aliases')
            ->setDescription(
                'Regenerates Location URL aliases (autogenerated) and migrates custom Location ' .
                'and global URL aliases with Legacy Storage Engine'
            )
            ->addOption(
                'iteration-count',
                'c',
                InputOption::VALUE_OPTIONAL,
                'Number of Locations fetched into memory and processed at once',
                self::DEFAULT_ITERATION_COUNT
            )
            ->addOption(
                'user',
                'u',
                InputOption::VALUE_OPTIONAL,
                'eZ Platform user used when running this command',
                self::DEFAULT_REPOSITORY_USER
            )
            ->setHelp(
                <<<EOT
The command <info>%command.name%</info> regenerates URL aliases for Locations and cleanups
corrupted URL aliases (pointing to non-existent Locations).
Existing aliases are archived (will redirect to the new ones).

<error>During the script execution the database should not be modified.</error>

Since this script can potentially run for a very long time, to avoid memory exhaustion run it in
production environment using <info>--env=prod</info> switch.

EOT
            );
    }

    /**
     * @param \Symfony\Component\Console\Input\InputInterface $input
     * @param \Symfony\Component\Console\Output\OutputInterface $output
     *
     * @throws \eZ\Publish\API\Repository\Exceptions\NotFoundException
     */
    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        $this->permissionResolver->setCurrentUserReference(
            $this->userService->loadUserByLogin($input->getOption('user'))
        );
    }

    /**
     * Regenerate URL aliases.
     *
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $iterationCount = (int)$input->getOption('iteration-count');

        $query = new LocationQuery(
            [
                'filter' => new Subtree('/1/'),
            ]
        );
        $pager = new Pagerfanta(
            new LocationSearchAdapter($query, $this->searchService)
        );
        $pager->setMaxPerPage($iterationCount);

        $output->writeln(
            sprintf(
                '<info>Found %d Locations. Regenerating System URL aliases...</info>',
                $pager->getNbResults()
            )
        );

        $progressBar = $this->getProgressBar($pager->getNbResults(), $output);
        $progressBar->start();

        $pagesCount = $pager->getNbPages();
        for ($currentPage = 1; $currentPage <= $pagesCount; ++$currentPage) {
            $pager->setCurrentPage($currentPage);
            $this->processLocations($pager, $progressBar, $output);
        }
        $progressBar->finish();
        $output->writeln('');

        $output->writeln('<info>Cleaning up corrupted URL aliases...</info>');
        $corruptedAliasesCount = $this->urlAliasService->deleteCorruptedUrlAliases();
        $output->writeln("<info>Done. Deleted {$corruptedAliasesCount} entries.</info>");
    }

    /**
     * Return configured progress bar helper.
     *
     * @param int $maxSteps
     * @param \Symfony\Component\Console\Output\OutputInterface $output
     *
     * @return \Symfony\Component\Console\Helper\ProgressBar
     */
    protected function getProgressBar($maxSteps, OutputInterface $output): ProgressBar
    {
        $progressBar = new ProgressBar($output, $maxSteps);
        $progressBar->setFormat(
            ' %current%/%max% [%bar%] %percent:3s%% %elapsed:6s%/%estimated:-6s% %memory:6s%'
        );

        return $progressBar;
    }

    /**
     * Process single results page of fetched Locations.
     *
     * @param \Pagerfanta\Pagerfanta $pager
     * @param \Symfony\Component\Console\Helper\ProgressBar $progressBar
     * @param \Symfony\Component\Console\Output\OutputInterface $output
     */
    private function processLocations(Pagerfanta $pager, ProgressBar $progressBar, OutputInterface $output)
    {
        foreach ($pager as $location) {
            try {
                /** @var \eZ\Publish\API\Repository\Values\Content\Location $location */
                $this->urlAliasService->refreshSystemUrlAliasesForLocation($location);
            } catch (\Exception $e) {
                $contentInfo = $location->getContentInfo();
                $output->writeln('');
                $output->writeln(
                    sprintf(
                        '<error>Failed processing location %d - [%d] %s (%s: %s)</error>',
                        $location->id,
                        $contentInfo->id,
                        $contentInfo->name,
                        get_class($e),
                        $e->getMessage()
                    )
                );
            } finally {
                $progressBar->advance();
            }
        }
    }
}
