<?php
return array(
    array(
        1 => new \eZ\Publish\API\Repository\Values\Content\Section(
            array(
                "id" => 1,
                "name" => "Standard",
                "identifier" => "standard",
            )
        ),
        2 => new \eZ\Publish\API\Repository\Values\Content\Section(
            array(
                "id" => 2,
                "name" => "Users",
                "identifier" => "users",
            )
        ),
        3 => new \eZ\Publish\API\Repository\Values\Content\Section(
            array(
                "id" => 3,
                "name" => "Media",
                "identifier" => "media",
            )
        ),
        4 => new \eZ\Publish\API\Repository\Values\Content\Section(
            array(
                "id" => 4,
                "name" => "Setup",
                "identifier" => "setup",
            )
        ),
        5 => new \eZ\Publish\API\Repository\Values\Content\Section(
            array(
                "id" => 5,
                "name" => "Design",
                "identifier" => "design",
            )
        ),
        6 => new \eZ\Publish\API\Repository\Values\Content\Section(
            array(
                "id" => 6,
                "name" => "Protected",
                "identifier" => "protected",
            )
        ),
    ),
    array(
        "standard" => 1,
        "users" => 2,
        "media" => 3,
        "setup" => 4,
        "design" => 5,
        "protected" => 6,
    ),
    array(
        "2" => array(
                    4 => true,
                    10 => true,
                    11 => true,
                    12 => true,
                    13 => true,
                    14 => true,
                    42 => true,
                ),
        "3" => array(
                    41 => true,
                    49 => true,
                    50 => true,
                    51 => true,
                    57 => true,
                    58 => true,
                    59 => true,
                    60 => true,
                    61 => true,
                    62 => true,
                    63 => true,
                    64 => true,
                    66 => true,
                    200 => true,
                    201 => true,
                ),
        "4" => array(
                    45 => true,
                    52 => true,
                ),
        "5" => array(
                    54 => true,
                    56 => true,
                ),
        "1" => array(
                    65 => true,
                    67 => true,
                    68 => true,
                    69 => true,
                    70 => true,
                    71 => true,
                    72 => true,
                    73 => true,
                    74 => true,
                    75 => true,
                    76 => true,
                    77 => true,
                    78 => true,
                    79 => true,
                    80 => true,
                    81 => true,
                    82 => true,
                    83 => true,
                    84 => true,
                    85 => true,
                    86 => true,
                    87 => true,
                    88 => true,
                    89 => true,
                    90 => true,
                    91 => true,
                    92 => true,
                    93 => true,
                    94 => true,
                    95 => true,
                    96 => true,
                    97 => true,
                    98 => true,
                    99 => true,
                    100 => true,
                    101 => true,
                    102 => true,
                    103 => true,
                    104 => true,
                    105 => true,
                    106 => true,
                    107 => true,
                    108 => true,
                    109 => true,
                    110 => true,
                    111 => true,
                    112 => true,
                    113 => true,
                    114 => true,
                    115 => true,
                    116 => true,
                    117 => true,
                    118 => true,
                    119 => true,
                    120 => true,
                    121 => true,
                    122 => true,
                    123 => true,
                    124 => true,
                    125 => true,
                    126 => true,
                    127 => true,
                    128 => true,
                    129 => true,
                    130 => true,
                    131 => true,
                    132 => true,
                    133 => true,
                    134 => true,
                    135 => true,
                    136 => true,
                    137 => true,
                    138 => true,
                    139 => true,
                    140 => true,
                    141 => true,
                    142 => true,
                    143 => true,
                    144 => true,
                    145 => true,
                    146 => true,
                    147 => true,
                    148 => true,
                    149 => true,
                    150 => true,
                    151 => true,
                    152 => true,
                    153 => true,
                    165 => true,
                    166 => true,
                    167 => true,
                    168 => true,
                    169 => true,
                    170 => true,
                    171 => true,
                    172 => true,
                    173 => true,
                    174 => true,
                    175 => true,
                    176 => true,
                    177 => true,
                    178 => true,
                    179 => true,
                    180 => true,
                    181 => true,
                    182 => true,
                    183 => true,
                    184 => true,
                    185 => true,
                    186 => true,
                    187 => true,
                    188 => true,
                    189 => true,
                    190 => true,
                    191 => true,
                    192 => true,
                    193 => true,
                    194 => true,
                    195 => true,
                    196 => true,
                    197 => true,
                    198 => true,
                    199 => true,
                    202 => true,
                    203 => true,
                    204 => true,
                    205 => true,
                    206 => true,
                    207 => true,
                    208 => true,
                    209 => true,
                    210 => true,
                    211 => true,
                    212 => true,
                    213 => true,
                    214 => true,
                    215 => true,
                    216 => true,
                    217 => true,
                    218 => true,
                    219 => true,
                    220 => true,
                    221 => true,
                    222 => true,
                    223 => true,
                    224 => true,
                    225 => true,
                ),
        "6" => array(
                    154 => true,
                    155 => true,
                    156 => true,
                    157 => true,
                    158 => true,
                    159 => true,
                    160 => true,
                    161 => true,
                    162 => true,
                    163 => true,
                    164 => true,
                ),
    ),
    6
);
