parameters:
    # RichText
    ezpublish.fieldType.ezrichtext.normalizer.document_type_definition.class: eZ\Publish\Core\FieldType\RichText\Normalizer\DocumentTypeDefinition
    ezpublish.fieldType.ezrichtext.converter.xslt.class: eZ\Publish\Core\FieldType\RichText\Converter\Xslt
    ezpublish.fieldType.ezrichtext.converter.aggregate.class: eZ\Publish\Core\FieldType\RichText\Converter\Aggregate
    ezpublish.fieldType.ezrichtext.converter.output.html5.class: eZ\Bundle\EzPublishCoreBundle\FieldType\RichText\Converter\Html5
    ezpublish.fieldType.ezrichtext.converter.edit.html5.class: eZ\Bundle\EzPublishCoreBundle\FieldType\RichText\Converter\Html5Edit
    ezpublish.fieldType.ezrichtext.converter.input.html5.class: eZ\Bundle\EzPublishCoreBundle\FieldType\RichText\Converter\Html5Input
    ezpublish.fieldType.ezrichtext.converter.programlisting.class: eZ\Publish\Core\FieldType\RichText\Converter\ProgramListing
    ezpublish.fieldType.ezrichtext.converter.link.class: eZ\Publish\Core\FieldType\RichText\Converter\Link
    ezpublish.fieldType.ezrichtext.converter.embed.class: eZ\Publish\Core\FieldType\RichText\Converter\Render\Embed
    ezpublish.fieldType.ezrichtext.converter.template.class: eZ\Publish\Core\FieldType\RichText\Converter\Render\Template
    ezpublish.fieldType.ezrichtext.renderer.class: eZ\Publish\Core\MVC\Symfony\FieldType\RichText\Renderer
    ezpublish.fieldType.ezrichtext.tag.namespace: fieldtypes.ezrichtext.tags
    ezpublish.fieldType.ezrichtext.style.namespace: fieldtypes.ezrichtext.styles
    ezpublish.fieldType.ezrichtext.embed.namespace: fieldtypes.ezrichtext.embed
    ezpublish.fieldType.ezrichtext.converter.dispatcher.class: eZ\Publish\Core\FieldType\RichText\ConverterDispatcher
    ezpublish.fieldType.ezrichtext.validator.xml.class: eZ\Publish\Core\FieldType\RichText\Validator
    ezpublish.fieldType.ezrichtext.validator.dispatcher.class: eZ\Publish\Core\FieldType\RichText\ValidatorDispatcher
    ezpublish.fieldType.ezrichtext.validator.internal_link.class: eZ\Publish\Core\FieldType\RichText\InternalLinkValidator
    ezpublish.fieldType.ezrichtext.resources: '%ezpublish.kernel.root_dir%/eZ/Publish/Core/FieldType/RichText/Resources'

    ezpublish.fieldType.ezrichtext.converter.input.xhtml5.resources: '%ezpublish.fieldType.ezrichtext.resources%/stylesheets/xhtml5/edit/docbook.xsl'
    ezpublish.fieldType.ezrichtext.converter.edit.xhtml5.resources: '%ezpublish.fieldType.ezrichtext.resources%/stylesheets/docbook/xhtml5/edit/xhtml5.xsl'
    ezpublish.fieldType.ezrichtext.converter.output.xhtml5.resources: '%ezpublish.fieldType.ezrichtext.resources%/stylesheets/docbook/xhtml5/output/xhtml5.xsl'
    ezpublish.fieldType.ezrichtext.converter.output.xhtml5.fragment.resources: '%ezpublish.fieldType.ezrichtext.resources%/stylesheets/xhtml5/output/fragment.xsl'

    ezpublish.fieldType.ezrichtext.validator.docbook.resources:
        - '%ezpublish.fieldType.ezrichtext.resources%/schemas/docbook/ezpublish.rng'
        - '%ezpublish.fieldType.ezrichtext.resources%/schemas/docbook/docbook.iso.sch.xsl'
    ezpublish.fieldType.ezrichtext.validator.output.ezxhtml5.resources:
        - '%ezpublish.fieldType.ezrichtext.resources%/schemas/ezxhtml5/output/ezxhtml5.xsd'

services:
    # RichText
    ezpublish.fieldType.ezrichtext.normalizer.input:
        class: '%ezpublish.fieldType.ezrichtext.normalizer.document_type_definition.class%'
        arguments:
            - 'section'
            - 'http://ez.no/namespaces/ezpublish5/xhtml5/edit'
            - '%ezpublish.kernel.root_dir%/eZ/Publish/Core/FieldType/RichText/Resources/dtd/ezxhtml5_edit_html_character_entities.dtd'

    ezpublish.fieldType.ezrichtext.converter.input.xhtml5.core:
        class: '%ezpublish.fieldType.ezrichtext.converter.input.html5.class%'
        arguments:
            - '%ezpublish.fieldType.ezrichtext.converter.input.xhtml5.resources%'
            - '@ezpublish.config.resolver'
        tags:
            - {name: ezpublish.ezrichtext.converter.input.xhtml5, priority: 50}

    # Note: should run before xsl transformation
    ezpublish.fieldType.ezrichtext.converter.input.xhtml5.programlisting:
        class: '%ezpublish.fieldType.ezrichtext.converter.programlisting.class%'
        tags:
            - {name: ezpublish.ezrichtext.converter.input.xhtml5, priority: 10}

    # Aggregate converter for XHTML5 input that other converters register to
    # through service tags.
    ezpublish.fieldType.ezrichtext.converter.input.xhtml5:
        class: '%ezpublish.fieldType.ezrichtext.converter.aggregate.class%'
        lazy: true

    ezpublish.fieldType.ezrichtext.converter.input.dispatcher:
        class: '%ezpublish.fieldType.ezrichtext.converter.dispatcher.class%'
        arguments:
            -
                http://docbook.org/ns/docbook: null
                http://ez.no/namespaces/ezpublish5/xhtml5/edit: '@ezpublish.fieldType.ezrichtext.converter.input.xhtml5'

    ezpublish.fieldType.ezrichtext.converter.link:
        class: '%ezpublish.fieldType.ezrichtext.converter.link.class%'
        arguments: ['@ezpublish.api.service.location', '@ezpublish.api.service.content', '@ezpublish.urlalias_router', '@?logger']
        tags:
            - {name: ezpublish.ezrichtext.converter.output.xhtml5, priority: 0}

    ezpublish.fieldType.ezrichtext.renderer:
        class: '%ezpublish.fieldType.ezrichtext.renderer.class%'
        arguments:
            - '@ezpublish.api.repository'
            - '@security.authorization_checker'
            - '@ezpublish.config.resolver'
            - '@templating'
            - '%ezpublish.fieldType.ezrichtext.tag.namespace%'
            - '%ezpublish.fieldType.ezrichtext.style.namespace%'
            - '%ezpublish.fieldType.ezrichtext.embed.namespace%'
            - '@?logger'
            - '%ezplatform.ezrichtext.custom_tags%'
            - '%ezplatform.ezrichtext.custom_styles%'

    ezpublish.fieldType.ezrichtext.converter.template:
        class: '%ezpublish.fieldType.ezrichtext.converter.template.class%'
        arguments:
            - '@ezpublish.fieldType.ezrichtext.renderer'
            - '@ezpublish.fieldType.ezrichtext.converter.output.xhtml5'
            - '@?logger'
        tags:
            - {name: ezpublish.ezrichtext.converter.output.xhtml5, priority: 10}

    ezpublish.fieldType.ezrichtext.converter.embed:
        class: '%ezpublish.fieldType.ezrichtext.converter.embed.class%'
        arguments:
            - '@ezpublish.fieldType.ezrichtext.renderer'
            - '@?logger'
        tags:
        - {name: ezpublish.ezrichtext.converter.output.xhtml5, priority: 10}

    ezpublish.fieldType.ezrichtext.converter.output.xhtml5.core:
        class: '%ezpublish.fieldType.ezrichtext.converter.output.html5.class%'
        arguments:
            - '%ezpublish.fieldType.ezrichtext.converter.output.xhtml5.resources%'
            - '@ezpublish.config.resolver'
        tags:
            - {name: ezpublish.ezrichtext.converter.output.xhtml5, priority: 50}

    # Note: should typically be the last one as it produces embeddable fragment
    ezpublish.fieldType.ezrichtext.converter.output.xhtml5.fragment:
        class: '%ezpublish.fieldType.ezrichtext.converter.xslt.class%'
        arguments: ['%ezpublish.fieldType.ezrichtext.converter.output.xhtml5.fragment.resources%']
        tags:
            - {name: ezpublish.ezrichtext.converter.output.xhtml5, priority: 100}

    # Aggregate converter for XHTML5 output that other converters register to
    # through service tags.
    ezpublish.fieldType.ezrichtext.converter.output.xhtml5:
        class: '%ezpublish.fieldType.ezrichtext.converter.aggregate.class%'
        lazy: true

    ezpublish.fieldType.ezrichtext.converter.edit.xhtml5:
        class: '%ezpublish.fieldType.ezrichtext.converter.edit.html5.class%'
        arguments:
            - '%ezpublish.fieldType.ezrichtext.converter.edit.xhtml5.resources%'
            - '@ezpublish.config.resolver'
        lazy: true

    ezpublish.fieldType.ezrichtext.validator.docbook:
        class: '%ezpublish.fieldType.ezrichtext.validator.xml.class%'
        arguments: ['%ezpublish.fieldType.ezrichtext.validator.docbook.resources%']

    ezpublish.fieldType.ezrichtext.validator.output.ezxhtml5:
        class: '%ezpublish.fieldType.ezrichtext.validator.xml.class%'
        arguments: ['%ezpublish.fieldType.ezrichtext.validator.output.ezxhtml5.resources%']

    ezpublish.fieldType.ezrichtext.validator.input.dispatcher:
        class: '%ezpublish.fieldType.ezrichtext.validator.dispatcher.class%'
        arguments:
            -
                http://docbook.org/ns/docbook: null
                http://ez.no/namespaces/ezpublish5/xhtml5/edit: null
                http://ez.no/namespaces/ezpublish5/xhtml5: '@ezpublish.fieldType.ezrichtext.validator.output.ezxhtml5'

    ezpublish.fieldType.ezrichtext.validator.internal_link:
        class: '%ezpublish.fieldType.ezrichtext.validator.internal_link.class%'
        arguments:
            - '@ezpublish.spi.persistence.cache.contentHandler'
            - '@ezpublish.spi.persistence.cache.locationHandler'

    # Symfony 3.4+ service definitions:
    eZ\Publish\Core\FieldType\RichText\CustomTagsValidator:
        public: false
        arguments: ['%ezplatform.ezrichtext.custom_tags%']
