name: TMP Assign Pull Request test

on:
  pull_request:

jobs:
  assign:
    uses: ibexa/gh-workflows/.github/workflows/pr-assign.yml@ibx-11778-update-deprecated-actions
    secrets:
      robot-token: ${{ secrets.EZROBOT_PAT }}
